// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	entity "github.com/iqbalbachmid/billing-engine/domain/entity"
	mock "github.com/stretchr/testify/mock"
)

// LoanRepository is an autogenerated mock type for the LoanRepository type
type LoanRepository struct {
	mock.Mock
}

type LoanRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *LoanRepository) EXPECT() *LoanRepository_Expecter {
	return &LoanRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: loan
func (_m *LoanRepository) Create(loan entity.Loan) (int, error) {
	ret := _m.Called(loan)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(entity.Loan) (int, error)); ok {
		return rf(loan)
	}
	if rf, ok := ret.Get(0).(func(entity.Loan) int); ok {
		r0 = rf(loan)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(entity.Loan) error); ok {
		r1 = rf(loan)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoanRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type LoanRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - loan entity.Loan
func (_e *LoanRepository_Expecter) Create(loan interface{}) *LoanRepository_Create_Call {
	return &LoanRepository_Create_Call{Call: _e.mock.On("Create", loan)}
}

func (_c *LoanRepository_Create_Call) Run(run func(loan entity.Loan)) *LoanRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entity.Loan))
	})
	return _c
}

func (_c *LoanRepository_Create_Call) Return(_a0 int, _a1 error) *LoanRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LoanRepository_Create_Call) RunAndReturn(run func(entity.Loan) (int, error)) *LoanRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: id
func (_m *LoanRepository) Delete(id int) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoanRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type LoanRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int
func (_e *LoanRepository_Expecter) Delete(id interface{}) *LoanRepository_Delete_Call {
	return &LoanRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *LoanRepository_Delete_Call) Run(run func(id int)) *LoanRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *LoanRepository_Delete_Call) Return(_a0 error) *LoanRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LoanRepository_Delete_Call) RunAndReturn(run func(int) error) *LoanRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields:
func (_m *LoanRepository) GetAll() ([]entity.Loan, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entity.Loan
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.Loan, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.Loan); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Loan)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoanRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type LoanRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
func (_e *LoanRepository_Expecter) GetAll() *LoanRepository_GetAll_Call {
	return &LoanRepository_GetAll_Call{Call: _e.mock.On("GetAll")}
}

func (_c *LoanRepository_GetAll_Call) Run(run func()) *LoanRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LoanRepository_GetAll_Call) Return(_a0 []entity.Loan, _a1 error) *LoanRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LoanRepository_GetAll_Call) RunAndReturn(run func() ([]entity.Loan, error)) *LoanRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: id
func (_m *LoanRepository) GetByID(id int) (entity.Loan, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 entity.Loan
	var r1 error
	if rf, ok := ret.Get(0).(func(int) (entity.Loan, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int) entity.Loan); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(entity.Loan)
	}

	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoanRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type LoanRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int
func (_e *LoanRepository_Expecter) GetByID(id interface{}) *LoanRepository_GetByID_Call {
	return &LoanRepository_GetByID_Call{Call: _e.mock.On("GetByID", id)}
}

func (_c *LoanRepository_GetByID_Call) Run(run func(id int)) *LoanRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *LoanRepository_GetByID_Call) Return(_a0 entity.Loan, _a1 error) *LoanRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LoanRepository_GetByID_Call) RunAndReturn(run func(int) (entity.Loan, error)) *LoanRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: loan
func (_m *LoanRepository) Update(loan entity.Loan) error {
	ret := _m.Called(loan)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entity.Loan) error); ok {
		r0 = rf(loan)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LoanRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type LoanRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - loan entity.Loan
func (_e *LoanRepository_Expecter) Update(loan interface{}) *LoanRepository_Update_Call {
	return &LoanRepository_Update_Call{Call: _e.mock.On("Update", loan)}
}

func (_c *LoanRepository_Update_Call) Run(run func(loan entity.Loan)) *LoanRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(entity.Loan))
	})
	return _c
}

func (_c *LoanRepository_Update_Call) Return(_a0 error) *LoanRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LoanRepository_Update_Call) RunAndReturn(run func(entity.Loan) error) *LoanRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewLoanRepository creates a new instance of LoanRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoanRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoanRepository {
	mock := &LoanRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
